#ifndef NOMI_EYES_H
#define NOMI_EYES_H

#include "lvgl.h"

typedef enum {
    NOMI_EXPRESSION_IDLE = 0,
    NOMI_EXPRESSION_RELAXED,
    NOMI_EXPRESSION_WAKE,
    NOMI_EXPRESSION_LISTENING,
    NOMI_EXPRESSION_THINKING,
    NOMI_EXPRESSION_RESPONDING,
    NOMI_EXPRESSION_CONFIRM,
    NOMI_EXPRESSION_ANGRY,
    NOMI_EXPRESSION_HAPPY,
    NOMI_EXPRESSION_EXCITED,
    NOMI_EXPRESSION_CURIOUS,
    NOMI_EXPRESSION_SPEECHLESS,
    NOMI_EXPRESSION_SURPRISED,
    NOMI_EXPRESSION_SHY,
    NOMI_EXPRESSION_SIGH,
    NOMI_EXPRESSION_SLEEPY,
    NOMI_EXPRESSION_SLEEP,
    NOMI_EXPRESSION_ALERT,
    NOMI_EXPRESSION_GENTLE_SMILE,
    NOMI_EXPRESSION_BIG_GRIN,
    NOMI_EXPRESSION_LAUGH,
    NOMI_EXPRESSION_TEARS_OF_JOY,
    NOMI_EXPRESSION_WINK,
    NOMI_EXPRESSION_PLAYFUL,
    NOMI_EXPRESSION_COOL,
    NOMI_EXPRESSION_IN_LOVE,
    NOMI_EXPRESSION_STARSTRUCK,
    NOMI_EXPRESSION_KISSY,
    NOMI_EXPRESSION_WARM_HUG,
    NOMI_EXPRESSION_BLISSFUL,
    NOMI_EXPRESSION_PROUD,
    NOMI_EXPRESSION_MISCHIEVOUS,
    NOMI_EXPRESSION_SILLY,
    NOMI_EXPRESSION_PARTY,
    NOMI_EXPRESSION_MAGICAL,
    NOMI_EXPRESSION_THANKFUL,
    NOMI_EXPRESSION_SKEPTICAL,
    NOMI_EXPRESSION_UNAMUSED,
    NOMI_EXPRESSION_EYE_ROLL,
    NOMI_EXPRESSION_DOUBTFUL,
    NOMI_EXPRESSION_AWKWARD,
    NOMI_EXPRESSION_EMBARRASSED,
    NOMI_EXPRESSION_BORED,
    NOMI_EXPRESSION_FOCUSED,
    NOMI_EXPRESSION_DETERMINED,
    NOMI_EXPRESSION_SUSPICIOUS,
    NOMI_EXPRESSION_SEARCHING,
    NOMI_EXPRESSION_ROBOT,
    NOMI_EXPRESSION_WORRIED,
    NOMI_EXPRESSION_ANXIOUS,
    NOMI_EXPRESSION_NERVOUS,
    NOMI_EXPRESSION_AFRAID,
    NOMI_EXPRESSION_PANIC,
    NOMI_EXPRESSION_SAD,
    NOMI_EXPRESSION_CRYING,
    NOMI_EXPRESSION_PLEADING,
    NOMI_EXPRESSION_DISAPPOINTED,
    NOMI_EXPRESSION_LONELY,
    NOMI_EXPRESSION_FRUSTRATED,
    NOMI_EXPRESSION_DIZZY,
    NOMI_EXPRESSION_KNOCKED_OUT,
    NOMI_EXPRESSION_SICK,
    NOMI_EXPRESSION_FREEZING,
    NOMI_EXPRESSION_RAGE,
    NOMI_EXPRESSION_COUNT
} nomi_expression_t;

void nomi_eyes_create(lv_obj_t * parent);
void nomi_eyes_set_carousel_period(uint32_t period_ms);
void nomi_eyes_trigger_clock(void);
nomi_expression_t nomi_eyes_current_expression(void);
const char * nomi_eyes_expression_name(nomi_expression_t expression);

#endif
